### ISSUE TITLE
Fire animation event only once scrollreveal

### ISSUE THREAD

**Issue by rubenheymans** [anijs/anijs#17]
this is my code:
data-anijs="if: scroll, on: window, do: bounceInLeft animated, before: scrollReveal, after: removeAnim"

the animation should fire only once after the page is loaded
this is not working: after: removeAnim 
everytime I scroll up and down the animation fires again

**Comment by darielnoel** [comment]
Hi, we launched [AniJS Studio](https://www.kickstarter.com/projects/888703031/anijs-studio) on KickStarter, that allow to designers and programmers add animations and interactions for Web pages in an easy and intuitive way. Please, take a look at the [project](https://www.kickstarter.com/projects/888703031/anijs-studio) and if you find it interesting or simply want to help us, you can make a small donation. I would be grateful, Greetings Dariel
