### ISSUE TITLE
Do Animation only once

### ISSUE THREAD

**Issue by kossmokvin** [anijs/anijs#18]
Hello. Thank you for your lib. It's very useful. I use the v 0.4.0.
 I need in some situations to do the animation only once. How can I do that?

For example:
- if:hover, do: hinge animated;

This constuction does the hinge everytime when I hover the element. But i need to do the Animation ONLY during the first hovering and then switch it off.

The helper: 'after:removeAnim' doesn't work. Why? It seems that I don't understand what it is actually doing. But it doesn't stop the animation after the first time was done.

Also the helper 'after:holdAnimClass' is not useful when I need the HINGE Animation, because using this helper after the hinge Animation the element doesn't come back its place - it disappears! 

I need the hinge animation only once, coming back the element at its old place and stop doing this animation after repeated hovering.

Please help me =)

**Comment by darielnoel** [comment]
Hi, we launched [AniJS Studio](https://www.kickstarter.com/projects/888703031/anijs-studio) on KickStarter, that allow to designers and programmers add animations and interactions for Web pages in an easy and intuitive way. Please, take a look at the [project](https://www.kickstarter.com/projects/888703031/anijs-studio) and if you find it interesting or simply want to help us, you can make a small donation. I would be grateful, Greetings Dariel
