### ISSUE TITLE
scroll event

### ISSUE THREAD

**Issue by olanchuy** [anijs/anijs#21]
Hi, great lib you have here :) Thanks for this. I have some question on scroll event.  The scroll event fires even the element is not visible on viewport(center of screen)?

**Comment by darielnoel** [comment]
Hi, we launched [AniJS Studio](https://www.kickstarter.com/projects/888703031/anijs-studio) on KickStarter, that allow to designers and programmers add animations and interactions for Web pages in an easy and intuitive way. Please, take a look at the [project](https://www.kickstarter.com/projects/888703031/anijs-studio) and if you find it interesting or simply want to help us, you can make a small donation. I would be grateful, Greetings Dariel
