### ISSUE TITLE
Additional animation configuration

### ISSUE THREAD

**Issue by rizkysyazuli** [anijs/anijs#24]
this is a great tool. very useful for css animation noobs like me :+1:

this tool would be a lot more awesome if we can have additional animation configuration such as `animation-delay`, `animation-duration`, etc.

**Comment by darielnoel** [comment]
Hi, we launched [AniJS Studio](https://www.kickstarter.com/projects/888703031/anijs-studio) on KickStarter, that allow to designers and programmers add animations and interactions for Web pages in an easy and intuitive way. Please, take a look at the [project](https://www.kickstarter.com/projects/888703031/anijs-studio) and if you find it interesting or simply want to help us, you can make a small donation. I would be grateful, Greetings Dariel
