### ISSUE TITLE
NodeJS, Express, Jade partial views issues

### ISSUE THREAD

**Issue by jferrell5** [anijs/anijs#25]
While test driving AniJS on a NodeJS/Express site using the Jade template engine, I have noticed that the animations do not work unless the anijs.js script reference is included directly in the partial view where the html tag to be animated with the "data-anijs" attribute exists. If the anijs script reference is included as part of a layout file(loaded into the page <head>) the anijs script loads prior to the view file's html, but no animation occurs. If the anijs script reference is included in the partial view, the animations work great. For obvious reasons I would rather have the script reference to anijs in the layout head tag, then just add the "data-anijs" attribute where desired throughout the site's views/partial views as with all other script libraries I am using. 

Am I missing something here or is this just the nature of the AniJS library? Good work btw.

**Comment by darielnoel** [comment]
Hi, we launched [AniJS Studio](https://www.kickstarter.com/projects/888703031/anijs-studio) on KickStarter, that allow to designers and programmers add animations and interactions for Web pages in an easy and intuitive way. Please, take a look at the [project](https://www.kickstarter.com/projects/888703031/anijs-studio) and if you find it interesting or simply want to help us, you can make a small donation. I would be grateful, Greetings Dariel
