### ISSUE TITLE
List of possible Events

### ISSUE THREAD

**Issue by Purus** [anijs/anijs#28]
Please let me know where can I find the list of all possible events.

I know we have click,dblclick, hover and some more. Am I missing any link in the Wiki for all possible events?

**Comment by darielnoel** [comment]
Hi, we launched [AniJS Studio](https://www.kickstarter.com/projects/888703031/anijs-studio) on KickStarter, that allow to designers and programmers add animations and interactions for Web pages in an easy and intuitive way. Please, take a look at the [project](https://www.kickstarter.com/projects/888703031/anijs-studio) and if you find it interesting or simply want to help us, you can make a small donation. I would be grateful, Greetings Dariel
