### ISSUE TITLE
anijs on joomla,please help

### ISSUE THREAD

**Issue by joomlolo** [anijs/anijs#29]
hello,sorry for my bad english,I try several times to make anijs working on joomla 3.3 but it still not working.I don t know why, I see the codepen, examples etc.. I do but the code has no effect, no class added.I test animation only (animate.css)it is working but no anijs, no class added, I check with firebug.Perhaps a problem with jquery noconflict ?( for example I have to use the word  "jQuery" instead of "$" for script ) I don t know,I need help please.I made a website just for this, for example, to test code:
http://s317686623.onlinehome.fr/ 
can you help me and tell me where is the problem ? I found your work beautiful,and i would like to use it.
thanks a lot
a joomla user

**Comment by darielnoel** [comment]
Hi, we launched [AniJS Studio](https://www.kickstarter.com/projects/888703031/anijs-studio) on KickStarter, that allow to designers and programmers add animations and interactions for Web pages in an easy and intuitive way. Please, take a look at the [project](https://www.kickstarter.com/projects/888703031/anijs-studio) and if you find it interesting or simply want to help us, you can make a small donation. I would be grateful, Greetings Dariel
