### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SergioMerida** [anijs/anijs#49]
I how are you, I have a question, I need to make some animations when you scroll, the problem that I have is: when I scroll first I saw the image(example) and then i see the animation, is something that I can do? thanks for anijs it's awesome

**Comment by darielnoel** [comment]
Hello Sergio, Maybe you need to hide the img by default via CSS3, using some properties like 'opacity', 'translate', etc. Then you can execute the animation and hold the final state of this. Best Regards, Dariel
