### ISSUE TITLE
AniJS work in Angular? (Question)

### ISSUE THREAD

**Issue by JuanLopezDev** [anijs/anijs#52]
Hello,
I used the following label to encourage an item and works:
```
 <img src="assets/img/logo.png" data-anijs="if: load, on: window, do: zoomIn animated">
```
But when my templates to integrate " Angular " is not working.
I have been researching and found the following:
```
 <img src="assets/img/logo.png" data-anijs="if: DOMContentLoaded, on: document, do: zoomIn animated">
```
Unfortunately it does not work either, I could help
Source: http://regularjs.github.io/blog/2014/07/26/2014-7-26-animation-rethink/#Angular

**Comment by darielnoel** [comment]
Hi Juan, 

The AniJS behavior is the below:
1 - The library script is loaded.
2 - By default AniJS travel through the current DOM nodes.

If you add another DOM elements dinamically(using angularJS) with new data-anijs sentences after this moment , you need to call the AniJS run function using Javascript.

//Traveled the DOM scope parsing all nodes with data-anijs tag.
AniJS.run();

Maybe the next [link](http://stackoverflow.com/questions/12304291/angularjs-how-to-run-additional-code-after-angularjs-has-rendered-a-template) can help.

Best Regards, Dariel

**Comment by JuanLopezDev** [comment]
Thank you! Dariel

**Comment by aimanharith67** [comment]
HI, I'm six years late for this, but can you give me the solution or example or any code that I can clone. I really want to use the aniJS on my Angular but I am too noob to do this and the solution that you give, I did not manage to do it. Hope you can help. Thank You
