### ISSUE TITLE
New maintenance team 

### ISSUE THREAD

**Issue by tgirardi** [anijs/anijs#57]
I've been asked to help in trying to assemble a team of people that can help with the maintenance of this project. It's been some months since the last commit and @darielnoel wants to keep the project alive, but he is scarce on time.

People **interested in helping** 🙋 please join this conversation. The more the better 😃

**Comment by darielnoel** [comment]
+1

**Comment by AshWilliams** [comment]
Count me in!

**Comment by darielnoel** [comment]
Thanks @tgirardi and @AshWilliams
 
Just as inspiration...

- [AniJS is sitepoint.com](http://www.sitepoint.com/?s=anijs)
- [AniJS is designyourway.net](http://www.designyourway.net/blog/resources/css-and-javascript-animation-libraries-to-create-awesome-effects/
)
- [Codegeekz](https://codegeekz.com/10-best-javascript-libraries-for-may-2014/)
- [Webdesignmoo](http://webdesignmoo.com/2014/21-fresh-javascript-libraries-2014/)

Something else:

![anijs](https://cloud.githubusercontent.com/assets/3312990/13799366/e8903a3a-eaf4-11e5-8f8f-27cba0b1c8aa.png)

**Comment by timelyportfolio** [comment]
:100:

**Comment by q2dg** [comment]
Well...it seems it hasn't been possible

**Comment by AnthonySLWhite** [comment]
Are you still hoping to keep the project alive?

**Comment by front10devs** [comment]
Yep. But we will need some help :)

**Comment by AnthonySLWhite** [comment]
True. But it's a start. I can talk with some developers to see if they can help and I'll get back to you

**Comment by AnthonySLWhite** [comment]
If he doesn't answer, who would be up to working on a forked version of this?

**Comment by darielnoel** [comment]
Hi guys, awesome!!! I can add you as a maintainer if you want.

Best, Dariel

**Comment by AnthonySLWhite** [comment]
Good to know your still hanging around @darielnoel 	
Go ahead and add me. I'll start by seeing who else wants to help.
After that I'll take a look at the issues one by one.

I'll try my best to continue to spread the magic of this great package you created.
Kudos for that by the way

**Comment by darielnoel** [comment]
Done @AnthonySLWhite , with a great power comes a great responsability. :)

**Comment by AnthonySLWhite** [comment]
Thank you Uncle Ben XD
But with all seriousness, I'll send you an email later today so we can keep in touch and decide the future of the repo if you still want to be apart of it.
