### ISSUE TITLE
Calling an animation on mouseenter and then another on mouse leave.

### ISSUE THREAD

**Issue by ssmith-wombatweb** [anijs/anijs#58]
I'm trying to create a menu that bounceInUp when mouseenter the main li. Then once the mouseleave the main li runs hinge and then removes all animations to make the element disappear. This is my code:
<section class="menuSample">
            <h2>An Animated Menu</h2>
            <nav data-anijs="if: mouseleave, on: .menuSample nav > ul > li, before: removeAnim, do: hinge animate visible, to: .menuSample ul li ul, after: removeAnim">
                <ul>
                    <li><span>Menu</span>
                        <ul data-anijs="if: mouseenter, on: .menuSample nav > ul > li, do:bounceInUp animated visible, to: .menuSample ul li ul">
                            <li>Home</li>
                            <li >Portfolio</li>
                            <li>About Us</li>
                            <li>Contact Us</li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </section>

I have tried removing the before from the mouseleave and it just removes all classes. I have tried just adding hinge, or hinge & animate and it doesn't leave the visible class. Any advice?

**Comment by ssmith-wombatweb** [comment]
`<section class="menuSample">
            <h2>An Animated Menu</h2>
            <nav data-anijs="if: mouseleave, on: .menuSample nav > ul > li, before: removeAnim, do: hinge animate visible, to: .menuSample ul li ul, after: removeAnim">
                <ul>
                    <li><span>Menu</span>
                        <ul data-anijs="if: mouseenter, on: .menuSample nav > ul > li, do:bounceInUp animated visible, to: .menuSample ul li ul">
                            <li>Home</li>
                            <li >Portfolio</li>
                            <li>About Us</li>
                            <li>Contact Us</li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </section>`

**Comment by ssmith-wombatweb** [comment]
Sorry this was my first time commenting on GitHub and I didn't realize code had to be entered differently.

**Comment by darielnoel** [comment]
Hi my friend:

Just do, this couple of changes:

1-)
- do: hinge _animate_ visible
- do: hinge **animated** visible

2-)

Remove the (before: removeAnim) from the nav **data-anijs**

I made an example for you ;)

http://codepen.io/darielnoel/pen/NNyGLY?editors=1000#anon-login

Have a nice Sunday

**Comment by ssmith-wombatweb** [comment]
Thank you. I can't believe I missed that.

**Comment by darielnoel** [comment]
;)
