### ISSUE TITLE
opposite of scrollreveal

### ISSUE THREAD

**Issue by fbrau** [anijs/anijs#68]
scrollreveal is great, and I would like to enhance the page by removing (in an animated manner)
some stuff details after I scroll down. For example

   Part 1
          some image
          some stunning text <-- when Part 2 reveals I want to fade this out
   Part 2
          some form

there are no samples on this, and I don't know if anijs can do this

**Comment by srikat** [comment]
You can use `To`definition for this.

Ex.:

```
if: scroll, on: window, do: fadeOut animated, to: .footer-widgets
```

With the above set as the value of `data-anijs` for an element, when that element is scrolled to, `.footer-widgets` will fade out.

**Comment by darielnoel** [comment]
+1
