### ISSUE TITLE
Q: Multiple data-anijs `if` one element

### ISSUE THREAD

**Issue by nea** [anijs/anijs#74]
Hi there

This is an awesome library. But I am asking myself if it is possible to register two animations per element? So, for example is it possible to define `if:click` and `if:mouseover` on the same element.

I haven't found anything while googling. Maybe you can help

Thanks a lot in advance

**Comment by iocouto** [comment]
@nea indeed, this is possible - there is an **[example in the Wiki](https://github.com/anijs/anijs/wiki/The-language)** which you can have a look at. You just declare both sentences in the same `data-anijs` attribute, making sure you end each one with a semicolon (`;`).

This issue can perhaps be closed.
